### ISSUE TITLE
文档呢

### ISSUE THREAD

**Issue by lisuchen002** [vtrbo/starter-vscode#1]
老北鼻，文档去哪里了？请写中文文档，并添加一些引经据典不好翻译的文字，中华文化博大精深，让国外友人也体验一下中华文化的魅力

**Comment by lisuchen002** [comment]
@vtrbo

**Comment by vtrbo** [comment]
> 老北鼻，文档去哪里了？请写中文文档，并添加一些引经据典不好翻译的文字，中华文化博大精深，让国外友人也体验一下中华文化的魅力

全局替换 ---name--- 为你的 VS Code 插件的名称就可以了
